from dataclasses import dataclass
from typing import Any, Callable, Generic, Optional, Type, TypeVar, NewType, Literal, Sequence
from XPPython3.xp_typing import *
kXPLM_Version: int
NO_PLUGIN_ID: int
PLUGIN_XPLANE: int
kVersion: int
NoFlag: XPLMKeyFlags
ShiftFlag: XPLMKeyFlags
OptionAltFlag: XPLMKeyFlags
ControlFlag: XPLMKeyFlags
DownFlag: XPLMKeyFlags
UpFlag: XPLMKeyFlags
CursorDefault: XPLMCursorStatus
CursorHidden: XPLMCursorStatus
CursorArrow: XPLMCursorStatus
CursorCustom: XPLMCursorStatus
CursorRotateSmall: XPLMCursorStatus
CursorRotateSmallLeft: XPLMCursorStatus
CursorRotateSmallRight: XPLMCursorStatus
CursorRotateMedium: XPLMCursorStatus
CursorRotateMediumLeft: XPLMCursorStatus
CursorRotateMediumRight: XPLMCursorStatus
CursorRotateLarge: XPLMCursorStatus
CursorRotateLargeLeft: XPLMCursorStatus
CursorRotateLargeRight: XPLMCursorStatus
CursorUpDown: XPLMCursorStatus
CursorDown: XPLMCursorStatus
CursorUp: XPLMCursorStatus
CursorLeftRight: XPLMCursorStatus
CursorRight: XPLMCursorStatus
CursorLeft: XPLMCursorStatus
CursorButton: XPLMCursorStatus
CursorHandle: XPLMCursorStatus
CursorFourArrows: XPLMCursorStatus
CursorSplitterH: XPLMCursorStatus
CursorSplitterV: XPLMCursorStatus
CursorText: XPLMCursorStatus
MouseDown: XPLMMouseStatus
MouseDrag: XPLMMouseStatus
MouseUp: XPLMMouseStatus
KEY_RETURN: int
KEY_ESCAPE: int
KEY_TAB: int
KEY_DELETE: int
KEY_LEFT: int
KEY_RIGHT: int
KEY_UP: int
KEY_DOWN: int
KEY_0: int
KEY_1: int
KEY_2: int
KEY_3: int
KEY_4: int
KEY_5: int
KEY_6: int
KEY_7: int
KEY_8: int
KEY_9: int
KEY_DECIMAL: int
VK_BACK: int
VK_TAB: int
VK_CLEAR: int
VK_RETURN: int
VK_ESCAPE: int
VK_SPACE: int
VK_PRIOR: int
VK_NEXT: int
VK_END: int
VK_HOME: int
VK_LEFT: int
VK_UP: int
VK_RIGHT: int
VK_DOWN: int
VK_SELECT: int
VK_PRINT: int
VK_EXECUTE: int
VK_SNAPSHOT: int
VK_INSERT: int
VK_DELETE: int
VK_HELP: int
VK_0: int
VK_1: int
VK_2: int
VK_3: int
VK_4: int
VK_5: int
VK_6: int
VK_7: int
VK_8: int
VK_9: int
VK_A: int
VK_B: int
VK_C: int
VK_D: int
VK_E: int
VK_F: int
VK_G: int
VK_H: int
VK_I: int
VK_J: int
VK_K: int
VK_L: int
VK_M: int
VK_N: int
VK_O: int
VK_P: int
VK_Q: int
VK_R: int
VK_S: int
VK_T: int
VK_U: int
VK_V: int
VK_W: int
VK_X: int
VK_Y: int
VK_Z: int
VK_NUMPAD0: int
VK_NUMPAD1: int
VK_NUMPAD2: int
VK_NUMPAD3: int
VK_NUMPAD4: int
VK_NUMPAD5: int
VK_NUMPAD6: int
VK_NUMPAD7: int
VK_NUMPAD8: int
VK_NUMPAD9: int
VK_MULTIPLY: int
VK_ADD: int
VK_SEPARATOR: int
VK_SUBTRACT: int
VK_DECIMAL: int
VK_DIVIDE: int
VK_F1: int
VK_F2: int
VK_F3: int
VK_F4: int
VK_F5: int
VK_F6: int
VK_F7: int
VK_F8: int
VK_F9: int
VK_F10: int
VK_F11: int
VK_F12: int
VK_F13: int
VK_F14: int
VK_F15: int
VK_F16: int
VK_F17: int
VK_F18: int
VK_F19: int
VK_F20: int
VK_F21: int
VK_F22: int
VK_F23: int
VK_F24: int
VK_EQUAL: int
VK_MINUS: int
VK_RBRACE: int
VK_LBRACE: int
VK_QUOTE: int
VK_SEMICOLON: int
VK_BACKSLASH: int
VK_COMMA: int
VK_SLASH: int
VK_PERIOD: int
VK_BACKQUOTE: int
VK_ENTER: int
VK_NUMPAD_ENT: int
VK_NUMPAD_EQ: int
