from dataclasses import dataclass
from typing import Any, Callable, Generic, Optional, Type, TypeVar, NewType, Literal, Sequence
from XPPython3.xp_typing import *    
WidgetClass_MainWindow: XPWidgetClass
MainWindowStyle_MainWindow: int
MainWindowStyle_Translucent: int
Property_MainWindowType: int
Property_MainWindowHasCloseBoxes: int
Message_CloseButtonPushed: int
WidgetClass_SubWindow: XPWidgetClass
SubWindowStyle_SubWindow: int
SubWindowStyle_Screen: int
SubWindowStyle_ListView: int
Property_SubWindowType: int
WidgetClass_Button: XPWidgetClass
PushButton: int
RadioButton: int
WindowCloseBox: int
LittleDownArrow: int
LittleUpArrow: int
ButtonBehaviorPushButton: int
ButtonBehaviorCheckBox: int
ButtonBehaviorRadioButton: int
Property_ButtonType: int
Property_ButtonBehavior: int
Property_ButtonState: int
Msg_PushButtonPressed: int
Msg_ButtonStateChanged: int
WidgetClass_TextField: XPWidgetClass
TextEntryField: int
TextTransparent: int
TextTranslucent: int
Property_EditFieldSelStart: int
Property_EditFieldSelEnd: int
Property_EditFieldSelDragStart: int
Property_TextFieldType: int
Property_PasswordMode: int
Property_MaxCharacters: int
Property_ScrollPosition: int
Property_Font: int
Property_ActiveEditSide: int
Msg_TextFieldChanged: int
WidgetClass_ScrollBar: XPWidgetClass
ScrollBarTypeScrollBar: int
ScrollBarTypeSlider: int
Property_ScrollBarSliderPosition: int
Property_ScrollBarMin: int
Property_ScrollBarMax: int
Property_ScrollBarPageAmount: int
Property_ScrollBarType: int
Property_ScrollBarSlop: int
Msg_ScrollBarSliderPositionChanged: int
WidgetClass_Caption: XPWidgetClass
Property_CaptionLit: int
WidgetClass_GeneralGraphics: XPWidgetClass
Ship: int
ILSGlideScope: int
MarkerLeft: int
_Airport: int
NDB: int
VOR: int
RadioTower: int
AircraftCarrier: int
Fire: int
MarkerRight: int
CustomObject: int
CoolingTower: int
SmokeStack: int
Building: int
PowerLine: int
VORWithCompassRose: int
OilPlatform: int
OilPlatformSmall: int
WayPoint: int
Property_GeneralGraphicsType: int
WidgetClass_Progress: XPWidgetClass
Property_ProgressPosition: int
Property_ProgressMin: int
Property_ProgressMax: int
