VPATH=..
TARGET=$(shell uname)

all : XPPython39.xpl XPPython310.xpl XPPython311.xpl
	@echo $^

# all : xppython3.xpl
# 	mkdir -p ../$(PLUGIN_PATH)/$(PLUGIN_DIR)
# 	cp xppython3.xpl ../$(PLUGIN_PATH)/$(PLUGIN_DIR)

include ../Makefile

