from typing import NewType, Tuple, Union, Optional
XPLMWidgetID = NewType('XPLMWidgetID', int)
XPWindowID = NewType('XPWindowID', int)
XPLMCommandRef = NewType('XPLMCommandRef', int)
XPLMMenuID = NewType('XPLMMenuID', int)
XPLMProbeRef = NewType('XPLMProbeRef', int)
XPLMObjectRef = NewType('XPLMObjectRef', int)
XPLMNavRef = NewType('XPLMNavRef', int)
XPLMMapLayerID = NewType('XPLMMapLayerID', int)
XPLMMapProjectionID = NewType('XPLMMapProjectionID', int)
XPLMFlightLoopID = NewType('XPLMFlightLoopID', int)
XPLMInstanceRef = NewType('XPLMInstanceRef', int)
XPLMAudioBus = NewType('XPLMAudioBus', int)
FMOD_STUDIO_SYSTEM = NewType('FMOD_STUDIO_SYSTEM', object)
FMOD_CHANNELGROUP = NewType('FMOD_CHANNELGROUP', object)
