from typing import Union, Callable, Any
from XPPython3.xp import XPLMMenuID, XPLMCommandRef

Menu_NoCheck = 0
Menu_Unchecked = 1
Menu_Checked = 2


def findPluginsMenu() -> XPLMMenuID: ...

def findAircraftMenu() -> XPLMMenuID: ...

def createMenu(name: Union[None, str] = None,
                   parentMenuID: Union[None, XPLMMenuID] = None,
                   parentItem: int = 0,
                   handler: Union[None, Callable[[Any, Any], None]] = None,
                   refCon: Union[None, Any] = None) -> XPLMMenuID: ...

def destroyMenu(menuID: XPLMMenuID) -> None: ...

def clearAllMenuItems(menuID: XPLMMenuID) -> None: ...

def appendMenuItem(menuID: Union[None, XPLMMenuID] = None, name: str = 'Item', refCon: Union[None, Any] = None) -> int: ...

def appendMenuItemWithCommand(menuID: Union[None, XPLMMenuID] = None,
                                  name: str = "Command",
                                  commandRef: Union[None, XPLMCommandRef] = None) -> int: ...

def appendMenuSeparator(menuID: Union[None, XPLMMenuID] = None) -> None: ...

def setMenuItemName(menuID: Union[None, XPLMMenuID] = None,
                        index: int = 0, name: str = "New Name") -> None: ...

def checkMenuItem(menuID: Union[None, XPLMMenuID] = None,
                      index: int = 0, checked: int = 2) -> None: ...

def checkMenuItemState(menuID: Union[None, XPLMMenuID] = None, index: int = 0) -> int: ...

def enableMenuItem(menuID: Union[None, XPLMMenuID] = None, index: int = 0, enabled: int = 1) -> None: ...

def removeMenuItem(menuID: Union[None, XPLMMenuID] = None, index: int = 0) -> None: ...
